services:
  - type: web
    name: mullak-validation-site
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SHEET_NAME
        value: Leads
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
        sync: false
